import { PortalModule } from '@angular/cdk/portal';
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';

import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { SwiperModule } from 'swiper/angular';

import {
  AdditionalOrderComponent,
  AddressDialogComponent,
  AddressFormComponent,
  AddressRadioItemSkeletonComponent,
  AlertComponent,
  AlternativeProductChoiceComponent,
  AspectRatioBoxComponent,
  BagChoiceComponent,
  BreadcrumbComponent,
  CarouselComponent,
  CategoryFlyoutFancyComponent,
  CategoryFlyoutFancyItemComponent,
  CategoryFlyoutSimpleComponent,
  ContactInfosComponent,
  EmbeddedVideoComponent,
  FeedbackFormComponent,
  FilterByComponent,
  ImageCarouselComponent,
  ListCardComponent,
  MainSectionSkeletonComponent,
  MobileSortFilterComponent,
  NavigationMenuComponent,
  PastOrderSkeletonComponent,
  ProductActionsComponent,
  ProductBadgeComponent,
  ProductBrandComponent,
  ProductCardSkeletonComponent,
  ProductDescriptionComponent,
  ProductDetailSkeletonComponent,
  ProductImageComponent,
  ProductListSkeletonComponent,
  ProductNameComponent,
  ProductPriceComponent,
  ProductShortfallInfoComponent,
  ReadMoreComponent,
  SearchNotFoundComponent,
  SearchResultSkeletonComponent,
  ShareButtonComponent,
  ShareButtonsComponent,
  ShortfallProductListItemComponent,
  SortByComponent,
  TimerBarComponent,
  UserShoppingListCartActionsComponent,
  UserShoppingListPublicComponent,
  SwiperBannerComponent,
  ProductDiscountLabelComponent,
} from './components';
import {
  ClickElsewhereDirective,
  ClickThrottleDirective,
  DeferLoadDirective,
  ElementBringForwardDirective,
  LazyLoadImageDirective,
  OnlyLettersDirective,
  OnlyNumbersDirective,
  SubmitThrottleDirective,
  TurnDeepInputAutocompleteOffDirective,
  ZoomImageDirective,
} from './directives';
import { ToasterComponent } from './features';
import {
  AccountDropdownComponent,
  AppLinksComponent,
  AuthLinksComponent,
  BrandLogoComponent,
  CheckoutPageBodyComponent,
  CustomerContactComponent,
  OrderAndDeliveryComponent,
  PaymentSecurityComponent,
  SearchBoxComponent,
  SocialMediaComponent,
  TopLinksComponent,
} from './layout';
import { CdkModule, MaterialModule, NgxCountdownDirective, NgxCountdownModule, SkeletonModule } from './modules';
import {
  DayNamePipe,
  FormatAmountPipe,
  FormatPricePipe,
  FormatUnitPipe,
  RestUrlPipe,
  SanitizeHtmlPipe,
  SearchBoldPipe,
  TodayTomorrowPipe,
} from './pipes';

@NgModule({
  declarations: [
    AccountDropdownComponent,
    BrandLogoComponent,
    SearchBoxComponent,
    TopLinksComponent,
    AdditionalOrderComponent,
    ToasterComponent,
    AlertComponent,
    AlternativeProductChoiceComponent,
    AspectRatioBoxComponent,
    BagChoiceComponent,
    BreadcrumbComponent,
    CarouselComponent,
    CategoryFlyoutFancyComponent,
    CategoryFlyoutFancyItemComponent,
    CategoryFlyoutSimpleComponent,
    EmbeddedVideoComponent,
    ImageCarouselComponent,
    ListCardComponent,
    NavigationMenuComponent,
    ReadMoreComponent,
    SearchNotFoundComponent,
    ShareButtonComponent,
    ShareButtonsComponent,
    TimerBarComponent,
    ProductListSkeletonComponent,
    ProductCardSkeletonComponent,
    MainSectionSkeletonComponent,
    ProductDetailSkeletonComponent,
    AddressRadioItemSkeletonComponent,
    SearchResultSkeletonComponent,
    PastOrderSkeletonComponent,
    ProductImageComponent,
    ProductNameComponent,
    TimerBarComponent,
    AddressFormComponent,
    AddressDialogComponent,
    ContactInfosComponent,
    FeedbackFormComponent,
    AppLinksComponent,
    CheckoutPageBodyComponent,
    CustomerContactComponent,
    OrderAndDeliveryComponent,
    SocialMediaComponent,
    PaymentSecurityComponent,
    FeedbackFormComponent,
    // Directives
    SubmitThrottleDirective,
    ClickElsewhereDirective,
    DeferLoadDirective,
    ElementBringForwardDirective,
    LazyLoadImageDirective,
    ZoomImageDirective,
    OnlyNumbersDirective,
    TurnDeepInputAutocompleteOffDirective,
    OnlyLettersDirective,
    ClickThrottleDirective,
    // Pipes
    FormatPricePipe,
    FormatAmountPipe,
    FormatUnitPipe,
    SanitizeHtmlPipe,
    RestUrlPipe,
    SearchBoldPipe,
    TodayTomorrowPipe,
    // Others
    ProductActionsComponent,
    ProductImageComponent,
    ProductNameComponent,
    ProductBrandComponent,
    ProductShortfallInfoComponent,
    ProductPriceComponent,
    ProductBadgeComponent,
    ProductDescriptionComponent,
    ShortfallProductListItemComponent,
    UserShoppingListPublicComponent,
    UserShoppingListCartActionsComponent,
    ProductShortfallInfoComponent,
    FilterByComponent,
    MobileSortFilterComponent,
    SortByComponent,
    AuthLinksComponent,
    OnlyNumbersDirective,
    TurnDeepInputAutocompleteOffDirective,
    DayNamePipe,
    ProductDiscountLabelComponent,
    SwiperBannerComponent,
  ],
  imports: [
    CommonModule,
    MaterialModule,
    RouterModule,
    ReactiveFormsModule,
    FormsModule,
    PortalModule,
    NgxCountdownModule,
    CdkModule,
    SkeletonModule,
    FontAwesomeModule,
    SwiperModule,
  ],
  exports: [
    AccountDropdownComponent,
    BrandLogoComponent,
    SearchBoxComponent,
    TopLinksComponent,
    AdditionalOrderComponent,
    AlertComponent,
    AlternativeProductChoiceComponent,
    AspectRatioBoxComponent,
    BagChoiceComponent,
    BreadcrumbComponent,
    CarouselComponent,
    CategoryFlyoutFancyComponent,
    CategoryFlyoutFancyItemComponent,
    CategoryFlyoutSimpleComponent,
    EmbeddedVideoComponent,
    ImageCarouselComponent,
    ListCardComponent,
    NavigationMenuComponent,
    ReadMoreComponent,
    SearchNotFoundComponent,
    ShareButtonComponent,
    ShareButtonsComponent,
    TimerBarComponent,
    ProductListSkeletonComponent,
    ProductCardSkeletonComponent,
    ProductDiscountLabelComponent,
    MainSectionSkeletonComponent,
    ProductDetailSkeletonComponent,
    AddressRadioItemSkeletonComponent,
    SearchResultSkeletonComponent,
    PastOrderSkeletonComponent,
    AddressFormComponent,
    AddressDialogComponent,
    ContactInfosComponent,
    FeedbackFormComponent,
    AppLinksComponent,
    CheckoutPageBodyComponent,
    CustomerContactComponent,
    OrderAndDeliveryComponent,
    SocialMediaComponent,
    PaymentSecurityComponent,
    AddressFormComponent,
    FeedbackFormComponent,
    ProductImageComponent,
    ProductShortfallInfoComponent,
    ProductNameComponent,
    TimerBarComponent,
    NgxCountdownDirective,
    // Directives
    ClickElsewhereDirective,
    DeferLoadDirective,
    SubmitThrottleDirective,
    ElementBringForwardDirective,
    LazyLoadImageDirective,
    ZoomImageDirective,
    OnlyNumbersDirective,
    TurnDeepInputAutocompleteOffDirective,
    OnlyLettersDirective,
    ClickThrottleDirective,
    // Pipes
    FormatPricePipe,
    FormatAmountPipe,
    FormatUnitPipe,
    SanitizeHtmlPipe,
    RestUrlPipe,
    SearchBoldPipe,
    TodayTomorrowPipe,
    // Modules
    NgxCountdownModule,
    CdkModule,
    SkeletonModule,
    FontAwesomeModule,
    // Others
    ProductActionsComponent,
    ProductImageComponent,
    ProductNameComponent,
    ProductBrandComponent,
    ProductPriceComponent,
    ProductBadgeComponent,
    ProductDescriptionComponent,
    ShortfallProductListItemComponent,
    UserShoppingListPublicComponent,
    UserShoppingListCartActionsComponent,
    FilterByComponent,
    MobileSortFilterComponent,
    SortByComponent,
    AuthLinksComponent,
    ReactiveFormsModule,
    FormsModule,
    DayNamePipe,
    ProductDiscountLabelComponent,
    SwiperBannerComponent,
  ],
  providers: [
    FormatPricePipe,
    FormatUnitPipe,
    FormatAmountPipe,
    RestUrlPipe,
    SanitizeHtmlPipe,
    SearchBoldPipe,
    TodayTomorrowPipe,
  ],
})
export class SharedModule {}
